### PR TITLE
Set return type in QueryPathIterator::current()

### LINKED ISSUE #27: Return type of QueryPath\QueryPathIterator::current() should either be compatible with IteratorIterator::current()
Looks like that class is not yet PHP 8.1 compatible?

### PR DESCRIPTION
**Pull request by Berdir**
Fixes #27

### CODE REVIEW

**Comment by jakejackson1** [comment]
Hi @Berdir, thanks for the contribution! 

[The PHP docs show](https://www.php.net/manual/en/class.iteratoriterator.php) that the method `current()` should have a type of `mixed`. Where did `Traversable` come from? 

[Looking at the docs for `Iterator`](https://www.php.net/manual/en/class.iterator.php), it seems like `current()` should have `#[ReturnTypeWillChange]` added to resolve the deprecation notice I imagine you are getting in PHP8.1. Would that resolve the problem for you?

**Comment by Berdir** [comment]
Yeah, I don't know what I was thinking, this makes no sense :) It didn't complain about it, strangely enough.

The annotation works, but I suppose you could also just set it to mixed. the annotation afaik is mostly for cases where you provide your own API/interface/base class and don't want to introduce a BC break (yet).

**Comment by Berdir** [comment]
I updated it to mixed now.

**Comment by jakejackson1** [comment]
> Yeah, I don't know what I was thinking, this makes no sense :) It didn't complain about it, strangely enough.
> 
> The annotation works, but I suppose you could also just set it to mixed. the annotation afaik is mostly for cases where you provide your own API/interface/base class and don't want to introduce a BC break (yet).

[Since `mixed` wasn't added as a valid return type until PHP8.0](https://www.php.net/manual/en/language.types.declarations.php), the annotation will be the best approach for now. [I've also merged an update to the automated test suite](https://github.com/GravityPDF/querypath/pull/29), so deprecation notices will at least show in the logs.

**Comment by jakejackson1** [comment]
@Berdir also, could you create a quick unit test for `QueryPathIterator::current()` to accompany this PR? Drop it in a new file at `tests/QueryPath/QueryPathIteratorTest.php` 👍

Thanks!

**Comment by jakejackson1** [comment]
@Berdir closing in favour of https://github.com/GravityPDF/querypath/pull/32. Thanks again for your contribution!

**Pull request closed without merging**
